spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: test-app
          uri: lb://test-app
          predicates:
            - Path=/test-app/**
          filters:
            - StripPrefix=1
        - id: test1-app
          uri: lb://test1-app
          predicates:
            - Path=/test1-app/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive
eureka:
  client:
    register-with-eureka: true #是否将自己注册到注册中心
    fetch-registry: true #是否从注册中心服务注册信息
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: debug
